### ISSUE TITLE
Attribute Error when trying to build the database

### ISSUE THREAD

**Issue by senarijit2021** [automationhacks/people-api#12]
Hi, 
When I am trying to run python build_database.py it is giving the following error:

`Traceback (most recent call last):
  File "build_database.py", line 15, in <module>
    db.create_all()
  File "/home/arijit/.local/share/virtualenvs/people-api-TjJHHjrg/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1039, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/arijit/.local/share/virtualenvs/people-api-TjJHHjrg/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1031, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/arijit/.local/share/virtualenvs/people-api-TjJHHjrg/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 962, in get_engine
    return connector.get_engine()
  File "/home/arijit/.local/share/virtualenvs/people-api-TjJHHjrg/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 555, in get_engine
    options = self.get_options(sa_url, echo)
  File "/home/arijit/.local/share/virtualenvs/people-api-TjJHHjrg/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 570, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/arijit/.local/share/virtualenvs/people-api-TjJHHjrg/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 914, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute`

**Comment by blulady** [comment]
Hey, I had the same problem. I had to update to running Flask-SQLAlchemy 2.5.1 and SQLAlchemy 1.4.3 and now it works fine.

**Comment by adailton1975** [comment]
When I try to run python build_database.py
 ModuleNotFoundError: No module named 'connexion'

**Comment by IvanFromUa** [comment]
> Hey, I had the same problem. I had to update to running Flask-SQLAlchemy 2.5.1 and SQLAlchemy 1.4.3 and now it works fine.

Thanks!
Just curiosity: how did you find that?

**Comment by automationhacks** [comment]
Version bump in Flask-SQLAlchemy, SQLAlchemy fixes the issue.
