### ISSUE TITLE
RuntimeError: Working outside of application context.

### ISSUE THREAD

**Issue by daredevil-8** [automationhacks/people-api#15]
Hi,
 I just cloned the codebase and completed the setup process.
I also updated all the dependencies to the latest versions.
when running the python build_database.py command i am getting below error

Traceback (most recent call last):
  File "build_database.py", line 15, in <module>
    db.create_all()
  File "/Users/manubharadwajhs/PycharmProjects/virtual_environments/people-api_2/lib/python3.8/site-packages/flask_sqlalchemy/extension.py", line 868, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "/Users/manubharadwajhs/PycharmProjects/virtual_environments/people-api_2/lib/python3.8/site-packages/flask_sqlalchemy/extension.py", line 839, in _call_for_binds
    engine = self.engines[key]
  File "/Users/manubharadwajhs/PycharmProjects/virtual_environments/people-api_2/lib/python3.8/site-packages/flask_sqlalchemy/extension.py", line 628, in engines
    app = current_app._get_current_object()  # type: ignore[attr-defined]
  File "/Users/manubharadwajhs/PycharmProjects/virtual_environments/people-api_2/lib/python3.8/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

**Comment by IvanFromUa** [comment]
I have the same issue

**Comment by automationhacks** [comment]
Thanks for reporting this issue. I am able to reproduce this error. Let me try to figure out why this is coming up.
