### ISSUE TITLE
Can't start server.py

### ISSUE THREAD

**Issue by ilysi** [automationhacks/people-api#19]
Can someone explain me what is wrong here?
I get following error:
PS C:\Users\\source\people-api> python server.py
>>
Traceback (most recent call last):
  File "C:\Users\\source\people-api\server.py", line 1, in <module>
    import connexion
  File "C:\Users\\.virtualenvs\course-api-framework-python-r-AymBON\Lib\site-packages\connexion\__init__.py", line 10, in <module>
    from .apps import AbstractApp  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\.virtualenvs\course-api-framework-python-r-AymBON\Lib\site-packages\connexion\apps\__init__.py", line 6, in <module>     
    from .abstract import AbstractApp  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\.virtualenvs\course-api-framework-python-r-AymBON\Lib\site-packages\connexion\apps\abstract.py", line 14, in <module>    
    from connexion.middleware import ConnexionMiddleware, MiddlewarePosition, SpecMiddleware
  File "C:\Users\\.virtualenvs\course-api-framework-python-r-AymBON\Lib\site-packages\connexion\middleware\__init__.py", line 2, in <module>
    from .main import ConnexionMiddleware, MiddlewarePosition  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\.virtualenvs\course-api-framework-python-r-AymBON\Lib\site-packages\connexion\middleware\main.py", line 23, in <module>  
    from connexion.middleware.security import SecurityMiddleware
  File "C:\Users\\.virtualenvs\course-api-framework-python-r-AymBON\Lib\site-packages\connexion\middleware\security.py", line 11, in <module>
    from connexion.security import SecurityHandlerFactory
  File "C:\Users\\.virtualenvs\course-api-framework-python-r-AymBON\Lib\site-packages\connexion\security.py", line 55, in <module>
    from connexion.decorators.parameter import inspect_function_arguments
  File "C:\Users\\.virtualenvs\course-api-framework-python-r-AymBON\Lib\site-packages\connexion\decorators\__init__.py", line 4, in <module>
    from .main import (  # noqa
  File "C:\Users\\.virtualenvs\course-api-framework-python-r-AymBON\Lib\site-packages\connexion\decorators\main.py", line 28, in <module>  
    from connexion.frameworks.flask import Flask as FlaskFramework
  File "C:\Users\\.virtualenvs\course-api-framework-python-r-AymBON\Lib\site-packages\connexion\frameworks\flask.py", line 123, in <module>
    class FlaskJSONProvider(flask.json.provider.DefaultJSONProvider):
                            ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'flask.json' has no attribute 'provider'

**Comment by ilysi** [comment]
Did get started, but have issues to run in on Postman or use the other operations in browser besides the create operation. I don't get it. I just wanted to learn how to test APIs and now are almost a week on trying to run the SUT API. :(
