### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: person

### ISSUE THREAD

**Issue by traw** [automationhacks/people-api#6]
On executing following commnad:
```
❯ python3 server.py
```
Do we need different steps to setup DB?
Thanks.
```
127.0.0.1 - - [24/May/2021 14:10:39] "GET //api/people HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: person

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/Users/user/projects/API/python_testautomationu.io/people-api/people.py", line 39, in read_all
    people = Person.query.order_by(Person.lname).all()
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2699, in all
    return self._iter().all()
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2834, in _iter
    result = self.session.execute(
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1677, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 329, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/Users/user/.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: person
[SQL: SELECT person.person_id AS person_person_id, person.lname AS person_lname, person.fname AS person_fname, person.timestamp AS person_timestamp
FROM person ORDER BY person.lname]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
```

**Comment by traw** [comment]
Needed to run the following command to create databases.
```
> python build_database.py

```

**Comment by automationhacks** [comment]
Glad you were able to self-serve. I'll close this issue.
